# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 13:12
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('address_street', models.CharField(blank=True, max_length=128)),
                ('address_no', models.SlugField(blank=True, max_length=4)),
                ('province', models.CharField(blank=True, choices=[('pomorskie', 'pomorskie'), ('warmińsko-mazurskie', 'warmińsko-mazurskie'), ('podlaskie', 'podlaskie'), ('mazowieckie', 'mazowieckie'), ('lubelskie', 'lubelskie'), ('podkarpackie', 'podkarpackie'), ('małopolskie', 'małopolskie'), ('śląskie', 'śląskie'), ('opolskie', 'opolskie'), ('dolnośląskie', 'dolnośląskie'), ('lubuskie', 'lubuskie'), ('zachodniopomorskie', 'zachodniopomorskie'), ('wielkopolskie', 'wielkopolskie'), ('kujawsko-pomorskie', 'kujawsko-pomorskie'), ('łódzkie', 'łódzkie'), ('świętokrzyskie', 'świętokrzyskie')], max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Podaj stanowisko lub nazwę projektu', max_length=256)),
                ('data_start', models.DateField()),
                ('data_end', models.DateField()),
                ('hours', models.IntegerField(default=160, validators=[django.core.validators.MaxValueValidator(320), django.core.validators.MinValueValidator(160)])),
                ('duties', models.TextField()),
                ('goal', models.CharField(max_length=1024)),
                ('skills', models.TextField()),
                ('studies', models.CharField(choices=[('1', 'animacja kultury'), ('2', 'antropologia'), ('3', 'archeologia'), ('4', 'bibliotekoznawstwo'), ('5', 'dziennikarstwo'), ('6', 'filologia angielska'), ('7', 'filologia francuska'), ('8', 'filologia polska'), ('9', 'filologia romańska'), ('10', 'filozofia'), ('11', 'grafika'), ('12', 'historia'), ('13', 'historia sztuki'), ('14', 'konserwacja zabytków'), ('15', 'kulturoznawstwo'), ('16', 'muzykologia'), ('17', 'pedagogika'), ('18', 'psychologia'), ('19', 'socjologia'), ('20', 'teatrologia'), ('21', 'zarządzanie kulturą')], max_length=64)),
                ('studies_other', models.CharField(blank=True, max_length=64)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern_app.Institution')),
            ],
        ),
    ]
